global:
  nfInstanceId: 73f113d5-24e4-4627-88e6-069111198d7e
  kibanaImport:
    enabled: false
  tracing:
    configmap: null
  housekeeping: null

app-filebeat-config:
  enabled: false

gloo-kubernetes:
  enabled: false

mock-udsf-client:
  enabled: false

registration-agent:
  enabled: false

udsf-data-repository:
  enabled: false

voltdb-operator:
  enabled: true
  global:
    rbac:
      pspEnabled: false
      create: true
  operator:
    createCustomResource: false
    serviceAccount:
      create: false
    resources:
      requests:
        cpu: 200m 
        memory: 250Mi
      limits:
        cpu: 400m 
        memory: 500Mi
    image:
      registry: harbor.rogers.lab/openet-software
    hyperkubeImage:
      registry: harbor.rogers.lab/openet-dependencies

voltdb-udsf:
  enabled: true
  global:
    rbac:
      pspEnabled: false
      create: true
  cluster:
    serviceAccount:
      create: false
    clusterSpec:
      persistentVolume:
        size: 40Gi
      resources:
        requests:
          cpu: 500m 
          memory: 2.8Gi
      image:
        registry: harbor.rogers.lab/openet-software

