global:
  glooRbac:
    create: true
  tls:
    enabled: true

gloo-kubernetes:
  gloo:
    gatewayProxies:
      gatewayProxy:
        service:
          type: NodePort
          httpNodePort: 32018
          httpsNodePort: 32019
    gloo:
      deployment:
        image:
          registry: harbor.rogers.lab/openet-dependencies/gloo-wrapper
  postInstall:
    image:
      registry: harbor.rogers.lab/openet-dependencies/alpine
  global:
    image:
      registry: harbor.rogers.lab/openet-dependencies/solo-io

keycloak:
  env:
    PROXY_FORWARD_HTTP_TO_HTTPS: "true"
  service:
    resources:
      requests:
        cpu: 1
        memory: 1G
  guiClientUrlMappings:
    app-selector:
    jaeger-ui:
    kibana:
    oc-gui:
    profilemanager:
    pcf-gui:
    odf-gui:
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

