global:
  glooRbac:
    create: true
  tls:
    enabled: false
  ocGui:
    externalWebOrigin: http://localhost:31020
    internalWebOrigin: http://gateway-proxy:80
  keycloak:
    externalWebOrigin: ""

gloo-kubernetes:
  gloo:
    gatewayProxies:
      gatewayProxy:
        service:
          type: NodePort
          httpNodePort: 31020
          httpsNodePort: 31021
    gloo:
      deployment:
        resources:
          requests:
            cpu: 100m
            memory: 600Mi
          limits:
            cpu: 200m
            memory: 800Mi
        image:
          registry: harbor.rogers.lab/openet-dependencies/gloo-wrapper
  postInstall:
    image:
      registry: harbor.rogers.lab/openet-dependencies/alpine
  global:
    image:
      registry: harbor.rogers.lab/openet-dependencies/solo-io

offercatalog-ui-api:
  enabled: true
  fullnameOverride: "oc-gui-offercatalog-ui-api"
  service:
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

offercatalog-gui-webapp:
  enabled: true
  fullnameOverride: "oc-gui-offercatalog-gui-webapp"
  config:
    currencyLabel:
      main: dollar
      fractional: cent
  service:
    resources:
      requests:
        cpu: 200m
        memory: 250Mi
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software 
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies 

timeofday-ui-api:
  enabled: true
  fullnameOverride: "oc-gui-timeofday-ui-api"
  service:
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

