- name: read params from input file
  vars:
    smoketests_param_file: "{{ lookup('file','ecsSmokeTestsParams.yaml') | from_yaml }}"
  set_fact:
    cluster: "{{ smoketests_param_file.cluster }}"

- name: run Jmeter script
  shell: cd ~/UTF/testHome && ls -l
  register: jmeter_script_results

- debug: var=jmeter_script_results  
