---
- name: generate template
  template:
    src: ns_resource.j2
    dest: ns_resource.json

- name: Create NS isntance resource
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/telco/api/nslcm/v2/ns_instances"
    method: POST
    body: "{{ lookup('file','ns_resource.json') }}"
    return_content: yes
    status_code: [200, 201]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
      Version: v2
  register: tca_ns_results

- debug: var=tca_ns_results.json
  when: debuglevel | int > 0

- set_fact:
    instance_id: "{{ tca_ns_results.json.id }}"

- name: encode values-cert-manager.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-cert-manager.yaml') | b64encode }} > values-cert-manager.base64

- name: encode values-consul.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-consul.yaml') | b64encode }} > values-consul.base64

- name: encode values-keycloak.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-keycloak.yaml') | b64encode }} > values-keycloak.base64

- name: encode values-jaeger.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-jaeger.yaml') | b64encode }} > values-jaeger.base64

- name: encode values-ads.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-ads.yaml') | b64encode }} > values-ads.base64

- name: encode values-udsf-volt.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-udsf-volt.yaml') | b64encode }} > values-udsf-volt.base64

- name: encode values-chf-udsf.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-chf-udsf.yaml') | b64encode }} > values-chf-udsf.base64

- name: encode values-slc-udsf.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-slc-udsf.yaml') | b64encode }} > values-slc-udsf.base64

- name: encode values-provisioning-volt.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-provisioning-volt.yaml') | b64encode }} > values-provisioning-volt.base64

- name: encode values-provisioning.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-provisioning.yaml') | b64encode }} > values-provisioning.base64

- name: encode values-ecs.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-ecs.yaml') | b64encode }} > values-ecs.base64

- name: encode values-oc-gui.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-oc-gui.yaml') | b64encode }} > values-oc-gui.base64

- name: encode values-strimzi-kafka-operator.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-strimzi-kafka-operator.yaml') | b64encode }} > values-strimzi-kafka-operator.base64

- name: encode values-odf.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-odf.yaml') | b64encode }} > values-odf.base64

- name: encode values-sftp.yaml
  shell: echo {{ lookup('file','../{{ values_folder }}/values-sftp.yaml') | b64encode }} > values-sftp.base64

  #- name: ecode values-monitoring.yaml
  #shell: echo {{ lookup('file','../{{ values_folder }}/values-monitoring.yaml') | b64encode }} > values-monitoring.base64

- name: generate template
  template:
    src: ns_instantiate.j2
    dest: ns_instantiate.json

- name: Instantiate NS
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/telco/api/nslcm/v2/ns_instances/{{ instance_id  }}/instantiate"
    method: POST
    body: "{{ lookup('file','ns_instantiate.json') }}"
    return_content: yes
    status_code: [200, 201, 202]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
      Version: v2
  register: tca_ns_instantiate_results

- debug: var=tca_ns_instantiate_results
  when: debuglevel | int > 0
