global:
  glooRbac:
    create: true
  tls:
    enabled: true

gloo-kubernetes:
  gloo:
    gloo:
      deployment:
        image:
          registry: harbor.rogers.lab/openet-dependencies/gloo-wrapper
  postInstall:
    image:
      registry: harbor.rogers.lab/openet-dependencies/alpine
  global:
    image:
      registry: harbor.rogers.lab/openet-dependencies/solo-io

keycloak:
  service:
    resources:
      requests:
        cpu: 1
        memory: 1G
  env:
    PROXY_FORWARD_HTTP_TO_HTTPS: "true"
  guiClientUrlMappings:
    oc-gui: https://10.249.235.11/offercatalog-gui/
    kibana: https://10.249.235.12/kibana/
    jaeger-ui: https://10.249.235.12/jaeger/
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

