global:
  glooRbac:
    create: true
  tls:
    enabled: true
  ocGui:
    externalWebOrigin: https://10.249.235.216
  keycloak:
    externalWebOrigin: ""

gloo-kubernetes:
  gloo:
    settings:
      integrations:
        consul:
          httpAddress: https://consul-consul-server.consul.svc:8501
    gatewayProxies:
      gatewayProxy:
        service:
          type: LoadBalancer
          loadBalancerIP: 10.249.235.216
          externalTrafficPolicy: Cluster
    gloo:
      deployment:
        resources:
          requests:
            cpu: 100m
            memory: 600Mi
          limits:
            cpu: 200m
            memory: 800Mi
        image:
          registry: harbor.rogers.lab/openet-dependencies/gloo-wrapper
  postInstall:
    image:
      registry: harbor.rogers.lab/openet-dependencies/alpine
  global:
    image:
      registry: harbor.rogers.lab/openet-dependencies/solo-io

offercatalog-ui-api:
  enabled: true
  service:
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

offercatalog-gui-webapp:
  enabled: true
  config:
    currencyLabel:
      main: dollar
      fractional: cent
  service:
    resources:
      requests:
        cpu: 200m
        memory: 250Mi
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software 
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies 

timeofday-ui-api:
  enabled: true
  service:
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies
