jaeger:
  nameOverride: "jaeger"
  fullnameOverride: "jaeger"
  provisionDataStore:
    cassandra: false
    elasticsearch: false
  storage:
    type: elasticsearch
    elasticsearch:
      host: monitoring-elasticsearch-es-http.monitoring
      scheme: https
      user: elastic
      usePassword: true
      existingSecret: monitoring-elasticsearch-es-elastic-user
      existingSecretKey: elastic
  agent:
    resources: 
      requests:
        cpu: 20m
        memory: 128Mi 
    tolerations:
    - key: "openet.com/elasticsearch"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    image: harbor.rogers.lab/openet-dependencies/jaegertracing/jaeger-agent
  collector:
    resources: 
      requests:
        cpu: 200m
        memory: 400Mi
    image: harbor.rogers.lab/openet-dependencies/jaegertracing/jaeger-collector
  query:
    oAuthSidecar:
      enabled: false
    resources:
      requests:
         cpu: 200m
         memory: 400Mi
    image: harbor.rogers.lab/openet-dependencies/jaegertracing/jaeger-query

