global:
  glooRbac:
    create: true
  tls:
    enabled: true
  ingress:
    protocols:
      https:
        certificate:
          additionalSANs:
            dnsNames:
              - localhost

gloo-kubernetes:
  gloo:
    gatewayProxies:
      gatewayProxy:
        service:
          type: NodePort
          httpNodePort: 32019
          httpsNodePort: 32020
    gloo:
      deployment:
        image:
          registry: harbor.rogers.lab/openet-dependencies/gloo-wrapper
  postInstall:
    image:
      registry: harbor.rogers.lab/openet-dependencies/alpine
  global:
    image:
      registry: harbor.rogers.lab/openet-dependencies/solo-io

keycloak:
  service:
    resources:
      requests:
        cpu: 1
        memory: 1G
  env:
    PROXY_FORWARD_HTTP_TO_HTTPS: "true"
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

