global:
  glooRbac:
    create: true
  nfInstanceId: 61d54609-4b76-4991-8c02-cf4ab277a2a3
  ecsNamespace: ecs
  tls:
    enabled: true
  serviceManagementGui:
    externalWebOrigin: https://10.249.235.207
  keycloak:
    externalWebOrigin: ""

gloo-kubernetes:
  gloo:
    settings:
      integrations:
        consul:
          httpAddress: https://consul-consul-server.consul.svc:8501
    gatewayProxies:
      gatewayProxy:
        service:
          type: LoadBalancer
          loadBalancerIP: 10.249.235.207
          externalTrafficPolicy: Cluster
    gloo:
      deployment:
        resources:
          requests:
            cpu: 100m
            memory: 600Mi
          limits:
            cpu: 200m
            memory: 800Mi
        image:
          registry: harbor.rogers.lab/openet-dependencies/gloo-wrapper
  postInstall:
    image:
      registry: harbor.rogers.lab/openet-dependencies/alpine
  global:
    image:
      registry: harbor.rogers.lab/openet-dependencies/solo-io
      
app-filebeat-config:
  enabled: true

app-selector-webapp:
  enabled: false

bulk-provisioning-orchestrator:
  enabled: true
  persistentVolume:
    storageClassName: vsphere-sc
  service:
    resources:
      requests:
        cpu: 1
        memory: 1.5G
      limits:
        cpu: 2
        memory: 2G
  initContainer:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

cog-pm:
  enabled: true
  installRsync: "false"
  service:
    resources:
      requests:
        cpu: 100m 
        memory: 256Mi
      limits:
        cpu: 2 
        memory: 2G
  camel:
    component:
      consul:
        agent:
          url: "https://${HOST_IP}:8501"
  autoscaling:
    maxReplicas: 1
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  housekeeping:
    image:
      registry: harbor.rogers.lab/openet-software
  rsync:
    image:
      registry: harbor.rogers.lab/openet-software
  filebeat:
    resources:
      requests:
        cpu: 40m 
        memory: 200Mi
      limits:
        cpu: 80m 
        memory: 400Mi
    image:
      registry: harbor.rogers.lab/openet-dependencies

custom-provisioning-gateway:
  enabled: true
  installRsync: "false"
  camel:
    component:
      consul:
        agent: 
          url: "https://${HOST_IP}:8501"
  service:
    resources:
      requests:
        cpu: 300m 
        memory: 1.5G
      limits:
        cpu: 2 
        memory: 2G 
  autoscaling:
    maxReplicas: 1
  initContainer:
    resources:
      requests:
        cpu: 0.1
        memory: 256Mi
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  housekeeping:
    image:
      registry: harbor.rogers.lab/openet-software
  rsync:
    image:
      registry: harbor.rogers.lab/openet-software
  filebeat:
    resources:
      requests:
        cpu: 40m 
        memory: 200Mi
      limits:
        cpu: 80m 
        memory: 400Mi
    image:
      registry: harbor.rogers.lab/openet-dependencies
  sbaRouter:
    initContainer:
      image:
        registry: harbor.rogers.lab/openet-software
    runtimeContainer:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 2
          memory: 2G
      image:
        registry: harbor.rogers.lab/openet-dependencies

job-scheduler:
  enabled: true
  installRsync: "false"
  fullnameOverride: "provisioning-job-scheduler"
  serviceDiscovery:
    consulClient:
      port: 8501
      secure: true
  service:
    resources:
      requests:
        cpu: 1 
        memory: 2G
      limits:
        cpu: 2
        memory: 3G
  initContainer:
    resources:
      requests:
        cpu: 100m 
        memory: 256Mi
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies
  housekeeping:
    image:
      registry: harbor.rogers.lab/openet-software
  rsync:
    image:
      registry: harbor.rogers.lab/openet-software
  filebeat:
    resources:
      requests:
        cpu: 40m 
        memory: 200Mi
      limits:
        cpu: 80m 
        memory: 400Mi
    image:
      registry: harbor.rogers.lab/openet-dependencies

product-provisioning-gateway:
  enabled: true
  installRsync: "false"
  service:
    resources:
      requests:
        cpu: 100m 
        memory: 256Mi
      limits:
        cpu: 2 
        memory: 2G
  camel:
    component:
      consul:
        agent:
          url: "https://${HOST_IP}:8501"
  autoscaling:
    maxReplicas: 1
  initContainer:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  housekeeping:
    image:
      registry: harbor.rogers.lab/openet-software
  rsync:
    image:
      registry: harbor.rogers.lab/openet-software
  filebeat:
    resources:
      requests:
        cpu: 40m 
        memory: 200Mi
      limits:
        cpu: 80m 
        memory: 400Mi
    image:
      registry: harbor.rogers.lab/openet-dependencies
  sbaRouter:
    initContainer:
      image:
        registry: harbor.rogers.lab/openet-software
    runtimeContainer:
      resources:
        requests:
          cpu: 100m 
          memory: 256Mi
        limits:
          cpu: 2
          memory: 2G
      image:
        registry: harbor.rogers.lab/openet-dependencies

profile-manager-gui-webapp:
  enabled: true
  service:
    resources:
      requests:
        cpu: 1 
        memory: 2G
      limits:
        cpu: 2
        memory: 3G
  initContainer:
    resources:
      requests:
        cpu: 100m 
        memory: 256Mi
    image:
      registry: harbor.rogers.lab/openet-software 
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

profile-manager-ui-api:
  enabled: true
  persistentVolume:
    storageClassName: vsphere-sc
  service:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2
        memory: 2G
  initContainer:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies

provisioning:
  enabled: false
  installRsync: "false"

registration-agent:
  enabled: false

rsyncd:
  enabled: false
  installRsyncInit: false
  installAwsS3SyncInit: false
  installGitSyncInit: false

sba-profile-manager:
  enabled: true
  installRsync: "false"
  serviceDiscovery:
    consulClient:
      port: 8501
      secure: true
  service:
    resources:
      requests:
        cpu: 200m 
        memory: 400Mi 
      limits:
        cpu: 2 
        memory: 2G
  jvm:
    options:
      user-defined-options:
      - "-Dlog4j.formatMsgNoLookups=true"
  initContainer:
    resources:
      requests:
        cpu: 100m 
        memory: 200Mi
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies
  housekeeping:
    image:
      registry: harbor.rogers.lab/openet-software
  rsync:
    image:
      registry: harbor.rogers.lab/openet-software
  filebeat:
    resources:
      requests:
        cpu: 40m 
        memory: 200Mi
      limits:
        cpu: 80m 
        memory: 400Mi
    image:
      registry: harbor.rogers.lab/openet-dependencies

sba-provisioning:
  enabled: true
  installRsync: "false"
  ecsNamespace: ecs
  serviceDiscovery:
    consulClient:
      port: 8501
      secure: true
  service:
    resources:
      requests:
        cpu: 300m 
        memory: 1.5G
      limits:
        cpu: 2 
        memory: 2G
  autoscaling:
    maxReplicas: 1
  jvm:
    options:
      user-defined-options:
      - "-Dlog4j.formatMsgNoLookups=true"
  initContainer:
    resources:
      requests:
        cpu: 100m 
        memory: 256Mi
    image:
      registry: harbor.rogers.lab/openet-software
      repository: sba-microservice/provisioning-service-server
      tag: 3.3.0-log4j-upgrade-B1
  chargingGatewayClient:
    initContainer:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      image:
        registry: harbor.rogers.lab/openet-software 
        repository: sba-microservice/charging-gateway-client-server
        tag: 1.0.0-log4j-upgrade-B1
    runtimeContainer:
      resources:
        requests:
          cpu: 100m 
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1G
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies
  housekeeping:
    image:
      registry: harbor.rogers.lab/openet-software
  rsync:
    image:
      registry: harbor.rogers.lab/openet-software
  filebeat:
    resources:
      requests:
        cpu: 40m 
        memory: 200Mi
      limits:
        cpu: 80m 
        memory: 400Mi
    image:
      registry: harbor.rogers.lab/openet-dependencies

sftp-server:
  enabled: false

voltdb-operator:
  enabled: false

voltdb-pm:
  enabled: false

