---
- name: Get clusters
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/hybridity/api/infra/k8s/clusters"
    method: GET
    return_content: yes
    status_code: [200]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
  register: tca_cluster_results

- name: get cluster vimID
  set_fact:
    vim_cluster_id: "{{ item.vimId }}"
  with_items: "{{ tca_cluster_results.json }}"
  when: item.clusterName == "{{ cluster }}"

- debug: var=vim_cluster_id

- name: Get cnf instances
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/telco/api/vnflcm/v2/vnf_instances"
    method: GET
    return_content: yes
    status_code: [200]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
      Version: V2
  register: tca_cnf_results

- name: get cnf instance ID for upgrade
  set_fact:
    cnf_for_upgrade_id: "{{ item.id }}"
  with_items: "{{ tca_cnf_results.json }}"
  when: item.vnfInstanceName == "{{ cnf }}"

- name: generate template
  template:
    src: cnf_upgrade.j2
    dest: cnf_upgrade.json

