- name: Install docker
  # ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod 777 get-docker.sh && ./get-docker.sh $$ docker version
  ansible.builtin.shell: apk add docker

- name: Install openrc
  # ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod 777 get-docker.sh && ./get-docker.sh $$ docker version
  ansible.builtin.shell: apk add openrc

- name: Install openrc
  # ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod 777 get-docker.sh && ./get-docker.sh $$ docker version
  ansible.builtin.shell: apk add --no-cache ca-certificates && update-ca-certificates

- name: copy crt file
  # ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod 777 get-docker.sh && ./get-docker.sh $$ docker version
  ansible.builtin.shell: mkdir /etc/docker/certs.d/harbor.rogers.lab && cp ca.crt /etc/docker/certs.d/harbor.rogers.lab

#- name: Sleep for 15 seconds and continue with play
#  wait_for:
#    timeout: 15

#- name: start docker
  # ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod 777 get-docker.sh && ./get-docker.sh $$ docker version
# ansible.builtin.shell: service docker status

- name: docker login to harbor
  ansible.builtin.shell: docker login --username {{ harbor_username }} --password {{ harbor_password }} https://harbor.rogers.lab

- name: Pull from exteral repo
  ansible.builtin.shell: docker pull harbor.rogers.lab/kir-test/jetstack/cert-manager-controller:v1.0.4