---
- name: read cluster template name and management cluster from input file
  vars: 
    cluster_config_file: "{{ lookup('file','mycluster.j2') | from_json }}"
  set_fact:
    cluster_template_name: "{{ cluster_config_file.clusterTemplateId }}"
    management_cluster_name: "{{ cluster_config_file.managementClusterId }}"
    cluster_name: "{{ cluster_config_file.name }}"    

- debug: var=cluster_template_name
- debug: var=management_cluster_name
  
- name: Get cluster templates
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/hybridity/api/infra/cluster-templates"
    method: GET
    return_content: yes
    status_code: [200]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
  register: tca_template_results

- name: get template ID
  set_fact:
    cluster_template_id: "{{ item.id }}"
  with_items: "{{ tca_template_results.json }}"
  when: item.name == "{{ cluster_template_name }}"

- debug: var=cluster_template_id

- name: Get clusters
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/hybridity/api/infra/k8s/clusters?filter=(eq,clusterName,{{ management_cluster_name }})"
    method: GET
    return_content: yes
    status_code: [200]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
  register: tca_cluster_results

- debug: var=tca_cluster_results

- set_fact:
    management_cluster_id: "{{ tca_cluster_results.json.id }}"

#- name: get management cluster ID
#  set_fact:
#    management_cluster_id: "{{ item.id }}"
#  with_items: "{{ tca_cluster_results.json }}"
#  when: item.clusterName == "{{ management_cluster_name }}"

- debug: var=management_cluster_id

- name: replace
  replace:
    path: mycluster.j2
    regexp: "{{ cluster_template_name }}"
    replace: "{{ cluster_template_id }}"

- name: replace
  replace:
    path: mycluster.j2
    regexp: "{{ management_cluster_name }}"
    replace: "{{ management_cluster_id }}"

