---

- name: generate template
  template:
    src: mycluster.j2
    dest: mycluster.json

- name: Create TKG Cluster
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/hybridity/api/infra/k8s/clusters"
    method: POST
    body: "{{ lookup('file','mycluster.json') }}"
    return_content: yes
    status_code: [200]
    body_format: json
    timeout: 180
    headers:
      x-hm-authorization: "{{ tca_authorization  }}"
  register: tca_cluster_results

- debug: var=tca_cluster_results
  when: debuglevel | int > 4
