- name: Install helm
  ansible.builtin.shell: sudo apt update && sudo apt upgrade && curl https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz -o helm-v3.5.4-linux-amd64.tar.gz && tar -zxvf helm-v3.5.4-linux-amd64.tar.gz && mv linux-amd64/helm /usr/local/bin/helm
