---
- name: read cluster name from input file
  vars: 
    ns_param_file: "{{ lookup('file','ecsNSParams.yaml') | from_yaml }}"
  set_fact:
    ns_instance_name: "{{ ns_param_file.nsInstanceName }}"      
    cluster_name: "{{ ns_param_file.cluster }}"
    values_folder: "{{ ns_param_file.valuesFolder }}"


- debug: var=cluster_name
  
- name: Get clusters
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/hybridity/api/infra/k8s/clusters?filter=(eq,clusterName,{{ cluster_name }})"
    method: GET
    return_content: yes
    status_code: [200]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
  register: tca_cluster_results

- set_fact:
    vim_cluster_id: "{{ tca_cluster_results.json[0].vimId }}"

#- name: get cluster vimID
#  set_fact:
#    vim_cluster_id: "{{ item.vimId }}"
#  with_items: "{{ tca_cluster_results.json }}"
#  when: item.clusterName == "{{ cluster_name }}"

- debug: var=vim_cluster_id

