---
- name: read cluster name from input file
  vars: 
    cnf_config_file: "{{ lookup('file','cnf_instantiate.j2') | from_json }}"
  set_fact:
    cluster_name: "{{ cnf_config_file.vimConnectionInfo[0].id }}"

- debug: var=cluster_name
  
- name: Get clusters
  uri:
    validate_certs: "{{ tca_validate_certificates }}"
    url: "https://{{ tca_fqdn }}/hybridity/api/infra/k8s/clusters"
    method: GET
    return_content: yes
    status_code: [200]
    body_format: json
    timeout: 180
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      x-hm-authorization: "{{ tca_authorization  }}"
  register: tca_cluster_results

- name: get cluster vimID
  set_fact:
    vim_cluster_id: "{{ item.vimId }}"
  with_items: "{{ tca_cluster_results.json }}"
  when: item.clusterName == "{{ cluster_name }}"

- debug: var=vim_cluster_id

- name: replace
  replace:
    path: cnf_instantiate.j2
    regexp: "{{ cluster_name }}"
    replace: "{{ vim_cluster_id }}"

