---
resource_types:
- name: ssh
  type: docker-image
  source:
    repository: quay.io/henry40408/concourse-ssh-resource

resources:
- name: ansible
  type: ssh
  source:
    host: 10.0.2.165
    user: vmware
    password: R0gers!23
- name: jmeter-vm
  type: ssh
  source:
    host: 10.0.2.146
    user: openet
    password: R0gers!23    
jobs:
- name: check-instantiates-nf
  public: true
  plan:
  - put: ansible
    params:
      interpreter: /bin/sh
      script: |
        rm -rf cicd && git clone https://gitea.rogers.lab/klukashin/cicd && ansible-playbook ./cicd/ansible/playbook-st-post1.yaml && rm -rf cicd
- name: check-pods
  public: true
  plan:
  - put: ansible
    params:
      interpreter: /bin/sh
      script: |
        rm -rf cicd && git clone https://gitea.rogers.lab/klukashin/cicd && ansible-playbook ./cicd/ansible/playbook-st-post2.yaml && rm -rf cicd

- name: check-pods
  public: true
  plan:
  - put: jmeter-vm
    params:
      interpreter: /bin/sh
      script: |
        rm -rf cicd && git clone https://gitea.rogers.lab/klukashin/cicd && ansible-playbook ./cicd/ansible/playbook-st-post3.yaml && rm -rf cicd
