fullnameOverride: "sftp-server"

autoscaling:
  enabled: true
  maxReplicas: 1

storage:
  createVolumeClaim: true
  class: "vsphere-sc"
  pvcName: "sftp-shared-volume"
  size: 10Gi
  dirName: "xdr"

usePublicKeysLogin: true
useOwnSshHostKey: true

nodeSelector:
  odf.openet.com/general: "true"

tolerations:
 - key: "openet.com/odf-general"
   operator: "Equal"
   value: "true"
   effect: "NoSchedule"

image:
  registry: harbor.rogers.lab/openet-dependencies

service:
  type: LoadBalancer
  loadBalancerIP: 10.249.235.5
  externalTrafficPolicy: Cluster
  port:
    number: 22
    type: sftp
    targetPort: 22
  resources:
    requests:
      cpu: 1
      memory: 2G
    limits:
      cpu: 1
      memory: 2G

user:
  username: openet
  password: Openet01
  uid: 1000
  gid: 1000

ssh:
  publicKeys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCt9o6Ov7len91TTwOK26T0UseR7RXN94/vsFsatR+NGWsktC1urdRk99PxGsYjPOYFy0gvGHw/IYtMP+TUyNEpbf+3NoVfLdMvXOPzID3xIMW+GXQjlSRFqvKecaa/KSI6pQYF0gkHSLR7GcA/oVgO9lZ3bhTqJRDVffactQvYoSXWtSESP7oN69l67zh0S8K50KK8wjXhxtEqJVZWsrympMYqkIKGWzpiAJlw3vnhHkNSi/mT/4+EZNDGgIIrmcJBY9ArTf2hpLsilABgWJt6q6xMCW0pViuT+vqAFzcqgRBfKK+3AJqaiZtAoMxc1J1e1jfKyBY4IWzl5WiXu0tAkmBO6dN477mQKRhDYW3CqKf2lWoly9V8c1WR3VvjiQJKfoMyyf3Vrcc1uJ1mNQuFak+ed+bb5Ex6XGBNOU7PdTn7jLVYeIZ2+OFx/lOEHSiOWXA6SqGBoYMr0cOaeKbZ5E0NGKEmw31uPc7CcXGRmi+uenAJBumvK67gV06Y5sU="

housekeeping:
  image:
    registry: harbor.rogers.lab/openet-software
  volumes:
    name: sftp-housekeeping-config-volume
  configMap:
    name: sftp-housekeeping-config-map

