fullnameOverride: "sftp-server"

autoscaling:
  enabled: true
  maxReplicas: 1

storage:
  createVolumeClaim: true
  class: "vsphere-sc"
  pvcName: "sftp-shared-volume"
  size: 10Gi
  dirName: "xdr"

usePublicKeysLogin: true
useOwnSshHostKey: true

nodeSelector:
  odf.openet.com/general: "true"

tolerations:
 - key: "openet.com/odf-general"
   operator: "Equal"
   value: "true"
   effect: "NoSchedule"

image:
  registry: harbor.rogers.lab/openet-dependencies

service:
  type: LoadBalancer
  loadBalancerIP: 10.249.235.55
  externalTrafficPolicy: Cluster
  port:
    number: 22
    type: sftp
    targetPort: 22
  resources:
    requests:
      cpu: 1
      memory: 2G
    limits:
      cpu: 1
      memory: 2G

user:
  username: openet
  password: Openet01
  uid: 1000
  gid: 1000

ssh:
  publicKeys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6TuED3bjD/K91UEjjLu1az2tGTgc8H2mxSqR1ufJGAy7XVZQbtNPUDbMJJM7f2AkxLkmhmJR2a9WjxVCd7/Rjo4gUcc/KsAVtk0DuYnMrEyyq1jfc+wNsGlRXpBU541Wqevx8+Rl1gMv9M0dJupHZbB+zgMGRs+18uKJ1T9+gGGzYtEARS/ljE3YNlfXA1XWO7NNE8FiliLmfCr46QarQahhxJcvWxum/FCy8007lOXupNqun+kiYPMcC0ZRmnxW4fN3Hzn/QMdRuS30wXoSaUt4KUUVTyw0xMp8SyEsR6kXgp7WqP6Ms5LmWKYiiHBQiSiqid9EdbA9FU3kMUoPPbLhi8KIbUXpn3qvyxiYlzNRvGBi5ElemlxGAH30kCu0NbjmRHLZp/xzMtx/Fora9TeuVblER2GctGRfIHFvaTPI1+HoWrr/nCNlSajLHurNzqalN5tuidlRtVA3ZYpNxNqTv/FAMVGID3hv819x3K6dQmhCpQRwVh8iyvy4OA4U="

housekeeping:
  image:
    registry: harbor.rogers.lab/openet-software
  volumes:
    name: sftp-housekeeping-config-volume
  configMap:
    name: sftp-housekeeping-config-map

