---
- name: "Deploy ECS Network Service"
  hosts: localhost
  gather_facts: no

  vars_files:
    - ./default/main.yaml
  roles:
    - { role: tca_api  }
    - { role: tca_ids_ns }      
    - { role: deploy_ns  }      
