---
- name: "Run Smoke Tests"
  hosts: localhost
  gather_facts: no

  vars_files:
    - ./default/main.yaml
  roles:
    - { role: smoke_tests_pre_check }          
    - { role: smoke_tests_post_deployment }
    - { role: smoke_tests_functional }
