---
- name: "Deploy AKO"
  hosts: localhost
  gather_facts: no

  vars_files:
    - ./default/main.yaml
  roles:
    - { role: tca_api }
    - { role: tca_ids_cnf }
    - { role: avi_segroup }        
    - { role: deploy_ako }      
