---
- name: "Create tkg cluster"
  hosts: localhost
  gather_facts: no

  vars_files:
    - ./default/main.yaml
  roles:
    - { role: tca_api  }
    - { role: tca_ids  }    
    - { role: create_cluster  }      
