---
- name: "Upgrade Network Function"
  hosts: localhost
  gather_facts: no

  vars_files:
    - ./default/main.yaml
  roles:
    - { role: harbor_push_charts }          
    - { role: harbor_push_images }
    - { role: tca_api }
    - { role: tca_ids_upgrade }      
    - { role: tca_build_csar }
    - { role: tca_upgrade_nf }      
