global:
  nfInstanceId: 73f113d5-24e4-4627-88e6-069111198d7e
  ingress:
    protocols:
      http:
        enabled: true
      https:
        enabled: false
  kibanaImport:
    enabled: false

gloo-kubernetes:
  enabled: false
  
app-filebeat-config:
  enabled: true

mock-udsf-client:
  enabled: false

registration-agent:
  enabled: false

udsf-data-repository:
  enabled: true
  global:
    tls:
       enabled: false
  autoscaling:
    maxReplicas: 1
  service:
    resources:
      requests:
        cpu: 400m 
        memory: 800Mi
  initContainer:
    image:
      registry: harbor.rogers.lab/openet-software
  runtimeContainer:
    image:
      registry: harbor.rogers.lab/openet-dependencies
  filebeat:
    resources:
      requests:
        cpu: 40m
        memory: 200Mi
    image:
      registry: harbor.rogers.lab/openet-dependencies
  housekeeping:
    image:
      registry: harbor.rogers.lab/openet-software
  udsfService:
    callback:
      serviceName: nchf-spendinglimitcontrol
      namespace: ecs

voltdb-operator:
  enabled: false

voltdb-udsf:
  enabled: false

